# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm ci
pages:
  stage: deploy
  script:
    - npm run build
    - cp -r build/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  variables:
    HOMEPAGE: "/$CI_PROJECT_NAME"
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: production
    url: $CI_PAGES_URL